# See: https://gohugo.io/getting-started/configuration/

####### BASE CONFIG #######
  baseURL = "https://yelosan.youronly.one/"                                              # .Site.BaseURL
  title = "Yelosan Publishing"                                                # .Site.Title; IMPT for Schema.org; OpenGraph; Twitter Cards; RDFa, Microdata, JSON-LD
  copyright = ""                                            # .Site.Copyright; leave empty to override theme
  timeZone = "Etc/UTC"


####### FRONTEND #######
  paginate = 8                                             # default: 10
  rssLimit = 25                                             # default: -1
  summaryLength = 240                                        # default: 70
  titleCaseStyle = "firstupper"                                     # default: AP; our choice: firstupper; backup: Chicago


####### LANGUAGE #######
  languageCode = "fil"
  defaultContentLanguage = "fil"                             # default: en
  defaultContentLanguageInSubdir = true                   # default: false
  hasCJKLanguage = true                                    # default: false
  # Our LANG: 'en', 'en-ph', 'fil', 'fil-hang', 'tl-tglg', 'zh-hant', 'zh-hans', 'zh-bopo', 'ja', 'ko'
  disableLanguages = ['en', 'fil-hang', 'zh-hant', 'zh-hans', 'zh-bopo', 'ja', 'ko']


####### BACKEND #######

  disableKinds = ["taxonomy", "term", "RSS", "robotsTXT"]
  #enableGitInfo = false                                     # default: false; for Git versioning
  enableMissingTranslationPlaceholders = true              # default: false
  #timeout = "30s"                                           # default: 30s


#######  #######  #######  #######  #######  #######  #######  #######
