# See: https://gohugo.io/getting-started/configuration/#merge-configuration-from-themes
_merge = "deep"

home = ["HTML"]
page = ["HTML"]
section = ["HTML", "JSON"]
taxonomy = ["HTML", "JSON"]
term = ["HTML", "JSON"]
