# See: https://gohugo.io/getting-started/configuration/#merge-configuration-from-themes
_merge = "deep"

subdir = "yoo"

rssfull = true

faviconcache = "fmgy"
faviconbuster = "TimmieIsMyFate"

favicon_mstilecolor = "#2b5797"

### BGN: Structured Data ###
  siteStartYear = 2020

  description = "Yelosan Publishing"
  license = "https://im.youronly.one/p/legal-notice/"
  keywords = ["Yelosan", "Yelosan Publishing", "yelosanpub", "YourOnly.One", "Yuki", "ᜌᜓᜃᜒ", "Chronicles"] # Can be overriden per page
  #images = ["https://rsc.youronly.one/img/y/YOOki_Chronicles.webp", "https://rsc.youronly.one/img/y/Yuki_flag-300h.webp", "https://rsc.youronly.one/img/y/Yuki_flag-square-300x.webp"]
### END: Structured Data ###

### BGN: Theme settings
  dateform        = "August 08, 2020"
  dateformShort   = "Aug 08"
  dateformNum     = "2020-07-23"
  dateformNumTime = "2020-07-23 17:08:24 +0800"

  homeSubtitle = "Mabuhay!"

  #backgroundImage = ""

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = true

  enableThemeToggle = false

  # Sharing buttons
  # There are a lot of buttons preconfigured. If you want to change them,
  # generate the buttons here: https://sharingbuttons.io
  # and add them into your own `layouts/partials/sharing-buttons.html`
  enableSharingButtons = false

  enableGlobalLanguageMenu = true

  justifyContent = false  # Set "text-align: justify" to .post-content.

  [footer]
    trademark = false
    rss = false
    copyright = false
    author = false

    #topText = []
    #bottomText = []

  [favicon.color]
    mask = "#252627"
    msapplication = "#252627"
    theme = "#252627"

  [logo]
    logoMark     = "₱"
    logoText     = "Yelosan"
    #logoHomeLink = "/"
    # Set true to remove the logo cursor entirely.
    # logoCursorDisabled = false
    # Set to a valid CSS color to change the cursor in the logo.
    # logoCursorColor    = "#67a2c9"
    # Set to a valid CSS time value to change the animation duration, "0s" to disable.
    # logoCursorAnimate  = "2s"
    # Append the current url pathname to logoText
    # logoCursorPathname = true

  #[params.portrait]
  #  path     = "img/image.jpg"
  #  alt      = "Portrait"
  #  maxWidth = "50px"
### END: Theme settings

### BGN: Other Settings ###
  [semweb]
    org = "yelosan"

    #isni = ""
    #issn = ""
    datecreated = "2020-07-01"
    isblog = false
    sameas = [
      "https://facebook.com/101597304949708/",
      "https://facebook.com/yelosanpub/",
      "https://codeberg.org/yelosan",
      "https://gitlab.com/yelosan",
      "https://github.com/yelosan"
    ]

    [[semweb.persons]]
      person = "yuki"
### END: Other Settings ###

### BGN: OLD ###
  # Paninap copyleft
  [params.copyleft]
    ContentOn = "Content on"
    SiteTitle = "Yelosan Publishing"
    UnlessOtherwise = ", unless otherwise specified."

  [params.name]
    yahuhanan = "Yahuhanan"
    yukia = "Yukia"
    sese = "Sese"
    cuneta = "Cuneta"
### END: OLD ###
